version: '3.9'

services:
  app:
    image: davidiniguezgomez/assignment1_davidiniguez_jaumesanchez:latest  
    environment:
      MONGO_URI: "mongodb://mongo:27017/"  # MongoDB URI
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports: 
      - 27017:27017

volumes:
  mongo_data: